[phases.setup]
nixPkgs = ["python312", "pango", "gobject-introspection", "gdk-pixbuf", "libffi", "harfbuzz", "fontconfig", "freetype"]

[phases.install]
cmds = ["pip install -r requirements/prod.txt"]
