# Generated by Django 5.0.14 on 2026-03-07 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="follow_up_emails",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"type": str, "subject": str, "body": str}]',
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="interview_questions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"question": str, "why_asked": str, "answer_framework": str}]',
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="keyword_matches",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='[{"keyword": str, "found": bool, "section_hint": str}]',
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="rewritten_resume_text",
            field=models.TextField(
                blank=True,
                help_text="Full AI-rewritten resume content tailored to the JD",
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="hire_probability",
            field=models.FloatField(blank=True, help_text="0.0-1.0", null=True),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="match_score",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="0-100", null=True
            ),
        ),
        migrations.CreateModel(
            name="LinkedInAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("headline", models.CharField(max_length=500)),
                ("about", models.TextField()),
                ("jd_text", models.TextField()),
                ("headline_rewrite", models.CharField(blank=True, max_length=500)),
                ("about_rewrite", models.TextField(blank=True)),
                ("suggested_skills", models.JSONField(blank=True, default=list)),
                ("recruiter_keywords", models.JSONField(blank=True, default=list)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tips", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linkedin_analyses",
                        to="analysis.jobdescription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
