# Generated by Django 5.0.14 on 2026-03-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0002_analysisresult_follow_up_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="share_token",
            field=models.CharField(
                blank=True,
                help_text="Public token for sharing score card",
                max_length=32,
                null=True,
                unique=True,
            ),
        ),
    ]
