# Generated by Django 5.0.14 on 2026-04-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analysis", "0003_add_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="rewritten_resume_json",
            field=models.JSONField(
                blank=True,
                help_text='Structured rewrite: {"name", "contact", "summary", "sections": [...]}',
                null=True,
            ),
        ),
    ]
